### ISSUE TITLE
UnsatisfiedLinkError on starting podman image

### ISSUE THREAD

**Issue by yellowHatpro** [thunderbiscuit/tatooine#12]
I built the podman image and started as mentioned in the documentation, and ended up getting following logs:
```
2023-03-26 13:25:56.664 [main] INFO  Application - Autoreload is disabled because the development mode is off.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /lib/x86_64-linux-gnu/li
bm.so.6: version `GLIBC_2.29' not found (required by /home/tatooine/.cache/JNA/temp/jna2242497406172792894.tmp)
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.Library$Handler.<init>(Library.java:192)
        at com.sun.jna.Native.load(Native.java:596)
        at com.sun.jna.Native.load(Native.java:570)
        at org.bitcoindevkit._UniFFILib$Companion$INSTANCE$2.invoke(bdk.kt:3541)   
        at org.bitcoindevkit._UniFFILib$Companion$INSTANCE$2.invoke(bdk.kt:258)    
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.bitcoindevkit._UniFFILib$Companion.getINSTANCE$lib(bdk.kt:258)      
        at org.bitcoindevkit.Blockchain.<init>(bdk.kt:988)
        at com.goldenraven.tatooine.FaucetWallet.<clinit>(FaucetWallet.kt:20)      
        at com.goldenraven.tatooine.ApplicationKt.module(Application.kt:27)        
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:150)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:276)
```

I saw similar issue in the padawan-wallet repo as well, and it was something about the 32-bit emulator and a 64-bit emulator. Is the same case here? 
How can we fix the issue in this case?
Any suggestions?

**Comment by prateek-singh-3212** [comment]
Facing the same issue.

**Comment by thunderbiscuit** [comment]
Oh nice you guys are trying out the faucet!

Ok so what _I think_ is happening here is probably that you're missing the Java Native Interface on your classpath. It's highly dependent on your OS/Docker/Podman image, so I forgot to add it to the readme here. You'll find info on how to fix it [here](https://github.com/bitcoindevkit/bdk-ffi/tree/master/bdk-jvm#known-issues).

You basically need to add JNA to your dependencies:
```kotlin
dependencies {
    // ...
    implementation("net.java.dev.jna:jna:5.12.1")
}
```

Let me know if that doesn't fix it!

**Comment by thunderbiscuit** [comment]
Also note that you don't need the Podman image to get it working/testing locally. You can just fire it up like any Gradle based application. Something like `./gradlew run` will probably fire up. 

Note that you have special local/testing credentials when you run it with the default settings, so you'll need to use those if you want to try to issue requests to the server.

**Comment by yellowHatpro** [comment]
@thunderbiscuit I installed the dependency, still gives the same error.

**Comment by prateek-singh-3212** [comment]
I am facing this issue while running the ktor server without creating the podman image.

```
 Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'bdkffi':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/bdkffi.dll) not found in resource path (C:\Users\91966\Android Studio\Git Projects\tatooine\app\build\classes\java\main;C:\Users\9196

```

**Comment by thunderbiscuit** [comment]
Oh I see. I bet you both are using a Windows operating system. The bdk-jvm library doesn't support Windows at the moment, but if you're interested in looking into that, we would definitely like the help! No one on the team has access to a Windows machine to test and develop the workflow, but it shouldn't be too different than what we have for Linux/macOS.

See [this issue](https://github.com/bitcoindevkit/bdk-ffi/issues/240) for details. Feel free to expand there or ask questions. Also, note that depending on your experience with Rust this might be a bit far of an ask, so don't feel obliged to work on this! I'm just pointing it out in case there is interest.

**Comment by yellowHatpro** [comment]
Interesting. I was dying to get my hands dirty in rust. But I would be needing some guidance on getting started with the project 😛. 
Is bdk discord server the right place to hit the doubts??

**Comment by prateek-singh-3212** [comment]
@thunderbiscuit Actully I want to run and server to test out the transaction filter in padawan wallet. So is there any other way?

Apart from this I also want to study the code of faucet because it seems intresting to me and I would love to extend its capablites as SOB.

Regarding the Contributing to bdk library to fix the above issue. I will definetly checkout the issue and update you there if I can help the team in resolving issue. 😊

**Comment by thunderbiscuit** [comment]
Yeah I think the only way to get it working on Windows is to add the feature to bdk-jvm.

It shouldn't be too hard, but it will require a decent amount of digging and fiddling. But yeah all the pieces are there for sure.
